version: '3'

services:
  my-rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    depends_on:
      - my-postgres-db
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgres://username:password@my-postgres-db:5432/my_database"  # Update with your database details

  my-postgres-db:
    image: postgres:14.10
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
